### PR TITLE
Update create2 deployment

### PR DESCRIPTION
**Pull request by salman01zp**
## Summary of changes
- [x] update create2 deployment script
- [x] deploy new contracts using create2

### Reference issue to close (if applicable)
- Closes 

-----
### Code Checklist 

- [ ] Tested
- [ ] Documented

### CODE REVIEW

**Comment by drewstone** [comment]
Is this ready to merge @salman01zp ?

**Comment by salman01zp** [comment]
Yes, it is now.. Will fix ts-check errors and make CI green

**Review by drewstone — APPROVED** [review]
Looks good except that we definitely need to figure out how to get the contract addresses to match across chains. Is there something in `create2` we overlooked @semaraugusto @salman01zp that makes it not possible given how we're handling it?

**Review by drewstone — APPROVED** [review]

**Comment by drewstone** [comment]
Awesome work @salman01zp @semaraugusto !

**Pull request merged**
