### PR TITLE
Change the localEvmBridge deployment script to lavage the DeterministicDeployFactory

### PR DESCRIPTION
**Pull request by AhmedKorim**
### Overview
Added the ability for `LocalEvmChain` to prepare the configuration required for the `Create2Vbridge` to create vAnchor which will use the `DeterministicDeployFactory`.

This change is required for the graph implementation so in `webb-graphql` repo we can use the theGraph factories for local evm chain

### CODE REVIEW

**Comment by drewstone** [comment]
This seems to have broken the `create2` tests @AhmedKorim. Also instead of overwriting the existing deployment scripts it would be better to write a new `create2` version of these.

**Comment by drewstone** [comment]
Also @AhmedKorim there should actually already be scripts for deploying with the deterministic deployer. @salman01zp can you link him here?

**Comment by salman01zp** [comment]
Yes, it's better to have a separate script for running localEvmChain using create2 for now. Here is the deployment [script](https://github.com/webb-tools/protocol-solidity/blob/main/scripts/evm/deployments/create2/deploymentScript.ts) for reference

**Comment by AhmedKorim** [comment]
@drewstone  @salman01zp SG ,will work on the separate to create2

**Pull request closed without merging**
